name: EMLRewards
version: 1.0-SNAPSHOT

main: org.EML.eMLRecompensas.EMLRecompensas
paperPluginLoader: org.EML.eMLRecompensas.EMLRecompensasLoader
api-version: '1.21.1'
load: POSTWORLD
commands:
  emlrec:
    description: Claim timed rewards.
    usage: /emlrec
permissions:
  emlrec.admin:
    description: Allows access to all EMLRec admin commands.
    default: op
  emlrec.rank.reward:
    description: Example custom reward permission.
    default: false
