name: EMLRewards
version: 1.0

main: org.EML.eMLRecompensas.EMLRecompensas
paperPluginLoader: org.EML.eMLRecompensas.EMLRecompensasLoader
api-version: '1.21.1'
load: POSTWORLD
commands:
  emlrew:
    description: Claim timed rewards.
    usage: /emlrew
permissions:
  emlrew.admin:
    description: Allows access to all EMLRewards admin commands.
    default: op
  emlrew.rank.reward:
    description: Example custom reward permission.
    default: false
